import { GROQ_GRADING_MODELS } from './data.js';
import { showApiKeyStatus } from './ui.js';

export function getGradingModel() {
  const saved = localStorage.getItem('groq_grading_model');
  if (saved === GROQ_GRADING_MODELS.fast || saved === GROQ_GRADING_MODELS.balanced) {
    return saved;
  }
  return GROQ_GRADING_MODELS.balanced;
}

export function saveGradingModel() {
  const select = document.getElementById('grading-model-select');
  if (select) localStorage.setItem('groq_grading_model', select.value);
}

export function updateAIStatusChip() {
  const apiKey = localStorage.getItem('api_key') || localStorage.getItem('gemini_api_key');
  const chip = document.getElementById('ai-status-chip');
  const text = document.getElementById('ai-status-text');

  if (!chip || !text) return;
  if (apiKey) {
    chip.classList.add('active');
    text.textContent = 'Groq Active';
  } else {
    chip.classList.remove('active');
    text.textContent = 'Not configured';
  }
}

export function saveApiKeyFromInput() {
  const input = document.getElementById('api-key-input');
  let key = input ? input.value : '';
  key = key.replace(/[^\x21-\x7E]/g, '');
  if (input) input.value = key;

  if (!key) {
    showApiKeyStatus('❌ Please enter an API key.', 'error');
    return;
  }
  if (!key.startsWith('gsk_')) {
    showApiKeyStatus('❌ This app uses Groq only. Keys start with gsk_ — get one at console.groq.com.', 'error');
    return;
  }
  localStorage.setItem('api_key', key);
  localStorage.setItem('api_provider', 'groq');
  updateAIStatusChip();
  showApiKeyStatus('✅ Groq API key saved!', 'success');
}

export function clearApiKey() {
  localStorage.removeItem('api_key');
  localStorage.removeItem('gemini_api_key');
  localStorage.removeItem('api_provider');
  const input = document.getElementById('api-key-input');
  if (input) input.value = '';
  updateAIStatusChip();
  showApiKeyStatus('🗑 API key cleared. Grading will use local fallback.', 'info');
}

export function hasGroqApiKey() {
  return !!localStorage.getItem('api_key');
}

export async function testApiConnection() {
  const input = document.getElementById('api-key-input');
  let key = input ? input.value : '';
  key = key.replace(/[^\x21-\x7E]/g, '');
  if (input) input.value = key;

  if (!key) {
    showApiKeyStatus('❌ Please enter an API key first.', 'error');
    return;
  }
  if (!key.startsWith('gsk_')) {
    showApiKeyStatus('❌ Groq keys start with gsk_. Get one at console.groq.com.', 'error');
    return;
  }
  showApiKeyStatus('🔄 Testing connection…', 'info');
  try {
    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + key,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: getGradingModel(),
        messages: [{role: 'user', content: 'Reply with exactly: OK'}]
      })
    });
    if (!response.ok) {
      if (response.status === 401) throw new Error('API_KEY_INVALID');
      throw new Error(`HTTP ${response.status}`);
    }
    const data = await response.json();
    const text = data.choices[0].message.content || '';
    if (text.toLowerCase().includes('ok')) {
      showApiKeyStatus('✅ Connection successful! Groq is ready.', 'success');
    } else {
      showApiKeyStatus('✅ Connected, got response: ' + text.substring(0, 50), 'success');
    }
  } catch (e) {
    const msg = e.message || String(e);
    if (msg.includes('API_KEY_INVALID') || msg.includes('401')) {
      showApiKeyStatus('❌ Invalid API key. Please check your key.', 'error');
    } else if (msg.includes('429')) {
      showApiKeyStatus('⚠️ Rate limited — hit the free tier limit. Try again shortly.', 'error');
    } else {
      showApiKeyStatus('❌ Connection failed: ' + msg.substring(0, 80), 'error');
    }
  }
}

export function getGradingPrompt(level, question, expectedAnswer, transcript) {
  let strictnessRules = '';

  if (level === 'N5') {
    strictnessRules = `
- **SPEECH-TO-TEXT HOMOPHONE RULE (CRITICAL)**: The transcript is generated by Speech-to-Text. STT frequently outputs the wrong kanji for homophones (words that sound identical, e.g. transcribing 'seiri' as 生理 instead of 整理). If a word in the transcript sounds exactly the same as the correct answer, you MUST treat it as perfectly correct. Do not penalize homophone kanji errors.
- Be EXTREMELY LENIENT with vocabulary. If the student uses a valid beginner alternative (e.g. わたしの instead of うちの), mark it correct.
- Prioritize correct pronunciation and basic meaning. Do not be a strict grammarian for N5.`;
  } else if (level === 'N4') {
    strictnessRules = `
- Be LENIENT with STT homophones (e.g. 生理 vs 整理). If it sounds the same, it is likely an STT artifact and should not be heavily penalized.
- Be moderately strict with vocabulary and grammar, but accept valid N4-level alternatives.`;
  } else {
    strictnessRules = `
- Expect precise vocabulary and correct grammar suitable for N3 level.
- You may forgive obvious STT kanji homophone errors, but hold the student to a high standard for particle usage and verb conjugation.`;
  }

  return `You are a Japanese language teacher grading a JLPT ${level} speaking practice answer.

Question asked: ${question}
Expected answer: ${expectedAnswer}
Student's spoken answer (speech-to-text transcript): ${transcript}

Evaluate the student's answer. Consider that the transcript comes from speech recognition and may contain minor recognition errors or kanji/katakana variations.

Respond ONLY with valid JSON (no markdown, no code fences, no explanation outside JSON):
{"correct":true or false,"score":0 to 100,"feedback":"1-2 sentence explanation in English","grammar_notes":"Grammar issues found, or empty string if none","particle_notes":"Particle usage issues, or empty string if none","vocabulary_notes":"Vocabulary issues, or empty string if none","suggested_answer":"The ideal answer if incorrect, or empty string if correct"}

CRITICAL JSON RULES:
- Do NOT use double quotes (") inside any of your text values. Use single quotes (') instead.
- Ensure the JSON is completely valid and properly escaped.
- Do not output any text before or after the JSON object.

Grading rules:${strictnessRules}
- Be STRICT with: particle usage (で/に/を/が/は/へ), verb tense and conjugation (ます/ました/ません), answering the actual question asked
- When providing feedback, cite the EXACT kanji or kana used in the transcript. If providing kana for kanji, use standard readings (e.g. 猫 is ねこ, do not write にゃん) unless specifically written as such in the transcript.
- If the transcript is garbled or empty, mark as incorrect with helpful feedback
- Set score 80-100 for correct answers, 40-79 for partially correct, 0-39 for incorrect.`;
}

export async function gradeWithAI(question, expectedAnswer, transcript) {
  const apiKey = localStorage.getItem('api_key') || localStorage.getItem('gemini_api_key');
  if (!apiKey) return null;

  try {
    const level = localStorage.getItem('jlpt_level') || 'N5';
    const prompt = getGradingPrompt(level, question, expectedAnswer, transcript);

    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + apiKey,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: getGradingModel(),
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: 'You are a Japanese language teacher.' },
          { role: 'user', content: prompt }
        ]
      })
    });
    if (!response.ok) {
      const errText = await response.text();
      console.error('Groq API failed:', response.status, errText);
      return null;
    }
    const data = await response.json();
    let text = data.choices?.[0]?.message?.content || '';

    if (!text) {
      console.error('AI returned empty text');
      return null;
    }

    text = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
    const startIdx = text.indexOf('{');
    const endIdx = text.lastIndexOf('}');
    if (startIdx !== -1 && endIdx !== -1) {
       text = text.substring(startIdx, endIdx + 1);
    } else {
      console.error('AI text did not contain JSON object:', text);
      return null;
    }

    let result;
    try {
      result = JSON.parse(text);
    } catch (pe) {
      console.error('Failed to parse AI JSON:', pe, 'Raw text:', text);
      return null;
    }

    return {
      correct: !!result.correct,
      score: typeof result.score === 'number' ? result.score : (result.correct ? 100 : 0),
      feedback: result.feedback || '',
      grammarNotes: result.grammar_notes || '',
      particleNotes: result.particle_notes || '',
      vocabularyNotes: result.vocabulary_notes || '',
      suggestedAnswer: result.suggested_answer || '',
      source: 'groq'
    };
  } catch (e) {
    console.error('AI grading error:', e);
    return null;
  }
}

export async function transcribeWithWhisper(audioBlob) {
  if (!hasGroqApiKey()) return null;
  const apiKey = localStorage.getItem('api_key');

  const formData = new FormData();
  formData.append('file', audioBlob, 'audio.webm');
  formData.append('model', 'whisper-large-v3-turbo');
  formData.append('language', 'ja');
  formData.append('temperature', '0');

  try {
    const response = await fetch('https://api.groq.com/openai/v1/audio/transcriptions', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + apiKey
      },
      body: formData
    });

    if (!response.ok) {
      console.error('Whisper API failed:', response.status);
      return null;
    }

    const data = await response.json();
    return data.text || '';
  } catch (e) {
    console.error('Transcription error:', e);
    return null;
  }
}

// ─────────────────────────────────────────────
// LOCAL FALLBACK GRADING
// ─────────────────────────────────────────────
const STRIP_RE = /[\s　、。！？・「」『』【】〜〈〉（）,，.]/g;

export async function isCorrectLocal(rawTranscript, answer) {
  const { katakanaToHiragana, transcriptToFurigana, transcriptToFuriganaForGrading } = await import('./parser.js');

  const normalizeAnswer = (s) => katakanaToHiragana(s).replace(STRIP_RE, '').toLowerCase();
  const normalizeTranscript = (raw, ans) => {
    const furigana = ans != null
      ? transcriptToFuriganaForGrading(raw, ans)
      : transcriptToFurigana(raw);
    return furigana.replace(STRIP_RE, '').toLowerCase();
  };

  const t = normalizeTranscript(rawTranscript, answer);
  const a = normalizeAnswer(answer);

  let sim = 0;
  if (t === a) sim = 1;
  else if (a.length === 0) sim = 0;
  else {
    const m = t.length, n = a.length;
    let prev = new Array(n + 1).fill(0);
    for (let i = 1; i <= m; i++) {
      const curr = new Array(n + 1).fill(0);
      for (let j = 1; j <= n; j++) {
        curr[j] = t[i-1] === a[j-1]
          ? prev[j-1] + 1
          : Math.max(prev[j], curr[j-1]);
      }
      prev = curr;
    }
    sim = prev[n] / a.length;
  }

  let finalScore = Math.round(sim * 100);
  let grammarNotes = '';
  let particleNotes = '';

  const particles = ['は', 'が', 'に', 'へ', 'で', 'を', 'の'];
  const missingParticles = [];
  particles.forEach(p => {
    const countA = (a.match(new RegExp(p, 'g')) || []).length;
    const countT = (t.match(new RegExp(p, 'g')) || []).length;
    if (countA > 0 && countT < countA) missingParticles.push(p);
  });

  const markers = ['ます', 'ました', 'ません', 'です', 'でした', 'ましょう', 'ますか', 'ませんか'];
  const missingVerbs = [];
  markers.forEach(marker => {
    const pattern = new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    const countA = (a.match(pattern) || []).length;
    const countT = (t.match(pattern) || []).length;
    if ((countA > 0 || countT > 0) && countA !== countT) missingVerbs.push(marker);
  });

  const particlePenalty = missingParticles.length * 10;
  const verbPenalty = missingVerbs.length * 15;
  if (particlePenalty + verbPenalty > 0) {
    finalScore -= particlePenalty + verbPenalty;
    if (missingParticles.length > 0) {
      particleNotes = 'Check your particles: ' + missingParticles.join(', ') + ' seems missing or incorrect.';
    }
    if (missingVerbs.length > 0) {
      grammarNotes = 'Check your verb tense/conjugation: ' + missingVerbs.join(', ') + ' seems missing or incorrect.';
    }
  }

  finalScore = Math.max(0, finalScore);
  const isCorrect = finalScore >= 65;

  return {
    correct: isCorrect,
    score: finalScore,
    feedback: isCorrect ? 'Answer matched (local check).' : 'Answer did not match closely enough (local check).',
    grammarNotes: grammarNotes,
    particleNotes: particleNotes,
    vocabularyNotes: '',
    suggestedAnswer: isCorrect ? '' : answer,
    source: 'local'
  };
}
